#!/bin/sh

# If less than 2 arguments
if [ $# -lt 2 ]; then
    echo -e "Usage: $0 serialport.dump graph.dot [functionName]"
else 
    echo -e "Generating $2..."
    java -jar dotprofiler.jar ../src/kdebug/symbolmap.gen $1 $3>$2
fi
